# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/pico/setup-makefiles.sh


## RIL

PRODUCT_COPY_FILES += \
    vendor/htc/pico/proprietary/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/htc/pico/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/htc/pico/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/htc/pico/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/htc/pico/proprietary/lib/liblge_security.so:system/lib/liblge_security.so \
    vendor/htc/pico/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/htc/pico/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/htc/pico/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/htc/pico/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/htc/pico/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/htc/pico/proprietary/lib/libauth.so:system/lib/libauth.so \
    vendor/htc/pico/proprietary/lib/libwms.so:system/lib/libwms.so \
    vendor/htc/pico/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/htc/pico/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/htc/pico/proprietary/lib/liboem_rapi.so:system/lib/liboem_rapi.so \
    vendor/htc/pico/proprietary/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/htc/pico/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/htc/pico/proprietary/lib/liblgeat.so:system/lib/liblgeat.so \
    vendor/htc/pico/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/htc/pico/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/htc/pico/proprietary/lib/liblgerft.so:system/lib/liblgerft.so \
    vendor/htc/pico/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/htc/pico/proprietary/lib/libbcmwl.so:system/lib/libbcmwl.so \
    vendor/htc/pico/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
    vendor/htc/pico/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/htc/pico/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/htc/pico/proprietary/lib/liblgdrm.so:system/lib/liblgdrm.so \
    vendor/htc/pico/proprietary/lib/libril.so:obj/lib/libril.so \
    vendor/htc/pico/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/htc/pico/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/htc/pico/proprietary/etc/flex/flex.xml:system/etc/flex/flex.xml \
    vendor/htc/pico/proprietary/bin/atd:system/bin/atd

## Audio

PRODUCT_COPY_FILES += \
    vendor/htc/pico/proprietary/lib/libaudioeq.so:system/lib/libaudioeq.so

## HAL
PRODUCT_COPY_FILES += \
    vendor/htc/pico/proprietary/lib/hw/lights.msm7k.so:system/lib/hw/lights.msm7k.so \
    vendor/htc/pico/proprietary/lib/hw/sensors.muscat.so:system/lib/hw/sensors.muscat.so

## EGL
PRODUCT_COPY_FILES += \
    vendor/htc/pico/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/htc/pico/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/htc/pico/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/htc/pico/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/htc/pico/proprietary/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/htc/pico/proprietary/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw

## Sensors
PRODUCT_COPY_FILES += \
    vendor/htc/pico/proprietary/bin/ami304d:system/bin/ami304d

## OMX
PRODUCT_COPY_FILES += \
    vendor/htc/pico/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
    vendor/htc/pico/proprietary/lib/libOmxAacEnc.so:system/lib/libOmxAacEnc.so \
    vendor/htc/pico/proprietary/lib/libOmxAdpcmDec.so:system/lib/libOmxAdpcmDec.so \
    vendor/htc/pico/proprietary/lib/libOmxAmrDec.so:system/lib/libOmxAmrDec.so \
    vendor/htc/pico/proprietary/lib/libOmxAmrEnc.so:system/lib/libOmxAmrEnc.so \
    vendor/htc/pico/proprietary/lib/libOmxAmrRtpDec.so:system/lib/libOmxAmrRtpDec.so \
    vendor/htc/pico/proprietary/lib/libOmxAmrwbDec.so:system/lib/libOmxAmrwbDec.so \
    vendor/htc/pico/proprietary/lib/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
    vendor/htc/pico/proprietary/lib/libOmxEvrcEnc.so:system/lib/libOmxEvrcEnc.so \
    vendor/htc/pico/proprietary/lib/libOmxEvrcHwDec.so:system/lib/libOmxEvrcHwDec.so \
    vendor/htc/pico/proprietary/lib/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    vendor/htc/pico/proprietary/lib/libOmxMp3Dec.so:system/lib/libOmxMp3Dec.so \
    vendor/htc/pico/proprietary/lib/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    vendor/htc/pico/proprietary/lib/libOmxOn2Dec.so:system/lib/libOmxOn2Dec.so \
    vendor/htc/pico/proprietary/lib/libOmxQcelp13Dec.so:system/lib/libOmxQcelp13Dec.so \
    vendor/htc/pico/proprietary/lib/libOmxQcelp13Enc.so:system/lib/libOmxQcelp13Enc.so \
    vendor/htc/pico/proprietary/lib/libOmxQcelpHwDec.so:system/lib/libOmxQcelpHwDec.so \
    vendor/htc/pico/proprietary/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/htc/pico/proprietary/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
    vendor/htc/pico/proprietary/lib/libOmxWmvDec.so:system/lib/libOmxWmvDec.so \
    vendor/htc/pico/proprietary/lib/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/htc/pico/proprietary/lib/libdivxdrmdecrypt.so:system/lib/libdivxdrmdecrypt.so

## Camera
PRODUCT_COPY_FILES += \
    vendor/htc/pico/proprietary/lib/libcamera.so:system/lib/libcamera.so \
    vendor/htc/pico/proprietary/lib/libcamera.so:obj/lib/libcamera.so \
    vendor/htc/pico/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/htc/pico/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/htc/pico/proprietary/lib/libmmipl.so:system/lib/libmmipl.so

## BT
PRODUCT_COPY_FILES += \
    vendor/htc/pico/proprietary/etc/firmware/BCM43291A0_003.001.013.0141.0153.hcd:system/etc/firmware/BCM43291A0_003.001.013.0141.0153.hcd

## WiFi
PRODUCT_COPY_FILES += \
    vendor/htc/pico/proprietary/etc/wl/rtecdc.bin:system/etc/wl/rtecdc.bin \
    vendor/htc/pico/proprietary/etc/wl/rtecdc-apsta.bin:system/etc/wl/rtecdc-apsta.bin
